# Generated by Django 5.1.4 on 2025-01-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tuser',
            table='t_user1',
        ),
    ]
